apiVersion: argoproj.io/v1alpha1
# Argo is implemented as a Kubernetes CRD (Custom Resource Definition)
# branch is set as a global variable so it can be accesses through workflow.parameters + how??
kind: Workflow
metadata:
  generateName: market-states
  labels:
    workflow: ci
spec:
  entrypoint: market-states
  templates:
    - name: market-states
      steps:
        # Step for cloning the repository and providing an Output which can be used by steps below.
        - - name: checkout
            # Uses the template "checkout"
            template: checkout

        - - name: build-and-push
            template: docker
            arguments:
              parameters:
                - name: cmd
                  value: "make docker_build && make docker_push"
              artifacts:
                - name: source
                  from: "{{steps.checkout.outputs.artifacts.source}}"

    # Checkout step template that can be copied directly into your own ci.yaml file.
    - name: checkout
      inputs:
        artifacts:
          - name: source
            path: /src
            git:
              repo: "{{workflow.parameters.repo}}"
              revision: "{{workflow.parameters.commit-id}}"
      outputs:
        artifacts:
          - name: source
            path: /src
      script:
        image: maerskao.azurecr.io/ci-runner:latest
        command: ["/bin/bash"]
        workingDir: /src
        source: |
          # Print branch name
          printf "#########################\n"
          printf "# branch                #\n"
          printf "#########################\n"
          printf "{{workflow.parameters.branch}}\n"

          # Print commit logs - 1 per line
          printf "#########################\n"
          printf "# git commit message(s) #\n"
          printf "#########################\n"
          echo '{{workflow.parameters.commit-log}}' | base64 -d

    # Template for building and pushing regular docker images
    - name: docker
      inputs:
        parameters:
          - name: cmd
        artifacts:
          - name: source
            path: /src
      container:
        image: maerskao.azurecr.io/ci-runner:latest
        command: [sh, -c]
        workingDir: /src
        args:
          [
            "export COMMIT_ID={{workflow.parameters.commit-id}} && {{inputs.parameters.cmd}}",
          ]
        resources:
          requests:
            memory: 256Mi
            cpu: 50m
          limits:
            memory: 512Mi
            cpu: 500m
